name: summary
channels:
- pytorch
- conda-forge
- defaults
dependencies:
- scrapy=1.5.0
- beautifulsoup4=4.6.0
- flake8=3.5.0
- gensim=3.1.0
- jupyter=1.0.0
- lxml=4.2.0
- matplotlib=2.2.2
- networkx=2.0
- nltk=3.2.5
- numpy=1.14.0
- pandas=0.22.0
- python=3.6.4
- pymongo=3.4.0
- requests=2.18.4
- scipy=1.0.0
- spacy=2.0.5
- pip:
  - camel==0.1.2
  - flake8-mypy==17.8.0
  # TODO upgrade sacred to 0.7.4 when it is released
  - git+https://github.com/IDSIA/sacred.git@aa85c80#egg=sacred
  - git+https://github.com/tagucci/pythonrouge.git@3cbec6#egg=pythonrouge
